exp_name: stream # Experiment names
seed: 1234 # Seed value

test_ckpt: "${dirs.outputs}/20251107_021814_ldf_stream/step_step=240000.ckpt"
test_vae_ckpt: "${dirs.outputs}/vae_1d_z4_step=300000.ckpt"
test_vae:
    target: models.vae_wan_1d.VAEWanModel
    ema_decay: 0.99
    params:
        input_dim: 263
        z_dim: 4
model:
    target: models.diffusion_forcing_wan.DiffForcingWanModel
    ema_decay: 0.99
    params:
        checkpoint_path: "${dirs.deps}/t5_umt5-xxl-enc-bf16/models_t5_umt5-xxl-enc-bf16.pth"
        tokenizer_path: "${dirs.deps}/t5_umt5-xxl-enc-bf16/google/umt5-xxl"
        input_dim: 4
        noise_steps: 10
        cfg_scale: 6.0