exp_name: stream_tiny # Experiment names
seed: 1234 # Seed value

test_ckpt: "${dirs.outputs}/20251219_01492_ldf_tiny_stream/step_step=200000.ckpt"
test_vae_ckpt: "${dirs.outputs}/vae_1d_z4_step=300000.ckpt"
test_vae:
    target: models.vae_wan_1d.VAEWanModel
    ema_decay: 0.99
    params:
        input_dim: 263
        z_dim: 4
model:
    target: models.diffusion_forcing_wan.DiffForcingWanModel
    ema_decay: 0.99
    params:
        crossmodules:
            - name: T5TextCrossModule
              len: 256
              dim: 768
              t5_size: "base"
              checkpoint_path: "${dirs.deps}/t5_umt5-base-enc/models_t5_umt5-base-enc.pth"
              tokenizer_path: "${dirs.deps}/t5_umt5-base-enc/google/umt5-base"
        input_dim: 4
        hidden_dim: 256
        ffn_dim: 1024
        freq_dim: 64
        num_heads: 8
        num_layers: 8
        time_embedding_scale: 1.0
        cfg_scale: 5.0
        prediction_type: "vel"
        causal: False
